# Generated by Django 5.0.1 on 2024-01-18 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulo',
            options={'ordering': ['-created'], 'verbose_name': 'article', 'verbose_name_plural': 'articles'},
        ),
    ]
